- name: Run ktlint with reviewdog
  # You may pin to the exact commit or the version.
  # uses: ScaCap/action-ktlint@58b3c386f5160049b0a1d0f986c56e0d0717140a
  uses: ScaCap/action-ktlint@1.3
  with:
    # GITHUB_TOKEN
    github_token: 
    # Report level for reviewdog [info,warning,error]
    level: # optional, default is error
    # Reporter of reviewdog command [github-pr-check,github-pr-review].
Default is github-pr-check.

    reporter: # optional, default is github-pr-check
    # Fails the current check if any error was found [true/false]
Default is false.

    fail_on_error: # optional, default is false
    # Print files relative to the working directory
    relative: # optional, default is true
    # Run KtLint with Android Kotlin Style Guide
    android: # optional, default is false
